### ISSUE TITLE
new 7zip jinja syntax leads to 'bad' version numbers

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt-winrepo-ng#1269]
@twangboy @fizmat The change in the 7zip.sls syntax as interesting as it looks, but unfortunately I think it leads to compiled sls files that are wrong. 
As far as I can tell it results in version that is not put in single quote and therefore will be read and misinterpreted as a floating point instead, and trailing zeros can be particularly 'bad' if memory serves me right? (and 7zip has loads ending in trailing zeroes ...)

this is what it compiles to now, I believe the resulting ```'version'``` ought to be in quotes?

```
  7zip:
    16.00.00.0:
      arch: x64
      full_name: 7-Zip 16.00 (x64 edition)
      install_flags: /qn /norestart
      installer: http://d.7-zip.org/a/7z1600-x64.msi
      locale: en_US
      msiexec: true
      reboot: false
      uninstall_flags: /qn /norestart
      uninstaller: http://d.7-zip.org/a/7z1600-x64.msi
    16.02.00.0:
      arch: x64
      full_name: 7-Zip 16.02 (x64 edition)
      install_flags: /qn /norestart
      installer: http://d.7-zip.org/a/7z1602-x64.msi
      locale: en_US
      msiexec: true
      reboot: false
      uninstall_flags: /qn /norestart
      uninstaller: http://d.7-zip.org/a/7z1602-x64.msi
    16.03.00.0:
      arch: x64
      full_name: 7-Zip 16.03 (x64 edition)
      install_flags: /qn /norestart
      installer: http://d.7-zip.org/a/7z1603-x64.msi
      locale: en_US
      msiexec: true
      reboot: false
      uninstall_flags: /qn /norestart
      uninstaller: http://d.7-zip.org/a/7z1603-x64.msi
    16.04.00.0:
      arch: x64
      full_name: 7-Zip 16.04 (x64 edition)
      install_flags: /qn /norestart
      installer: http://d.7-zip.org/a/7z1604-x64.msi
      locale: en_US
      msiexec: true
      reboot: false
      uninstall_flags: /qn /norestart
      uninstaller: http://d.7-zip.org/a/7z1604-x64.msi
    9.20.00.0:
      arch: x64
      full_name: 7-Zip 9.20 (x64 edition)
      install_flags: /qn /norestart
      installer: http://d.7-zip.org/a/7z920-x64.msi
      locale: en_US
      msiexec: true
      reboot: false
      uninstall_flags: /qn /norestart
      uninstaller: http://d.7-zip.org/a/7z920-x64.msi
```

as shown by ```salt mywinminion winrepo.show_sls salt-winrepo-ng.7zip --out=yaml```

**Comment by fizmat** [comment]
I think show_sld does not print the raw template output, even with the --out=yaml flag. It just formats the salt dictionary after salt already interpreted the sls, with whatever yaml formatting rules it has.

For example [svn](https://github.com/saltstack/salt-winrepo-ng/blob/master/svn.sls) has a very simple sls:
```
svn:
  '1.8.13':
    full_name: 'Subversion'
    installer: 'https://downloads.sourceforge.net/projects/win32svn/files/1.8.13/Setup-Subversion-1.8.13.msi'
    install_flags: '/quiet'
    uninstaller: 'https://downloads.sourceforge.net/projects/win32svn/files/1.8.13/Setup-Subversion-1.8.13.msi'
    uninstall_flags: '/qn /norestart'
    msiexec: True
    locale: en_US
    reboot: False
  '1.8.11':
    full_name: 'Subversion'
    installer: 'https://downloads.sourceforge.net/projects/win32svn/files/1.8.11/Setup-Subversion-1.8.11.msi'
    install_flags: '/quiet'
    uninstaller: 'https://downloads.sourceforge.net/projects/win32svn/files/1.8.11/Setup-Subversion-1.8.11.msi'
    uninstall_flags: '/qn /norestart'
    msiexec: True
    locale: en_US
    reboot: False
```

But it also results in unqouted version numbers when running through show_sls:

```
salt scw winrepo.show_sls salt-winrepo-ng.svn -t 120 --out=yaml
scw:
  svn:
    1.8.11:
      full_name: Subversion
      install_flags: /quiet
      installer: https://downloads.sourceforge.net/projects/win32svn/files/1.8.11/Setup-Subversion-1.8.11.msi
      locale: en_US
      msiexec: true
      reboot: false
      uninstall_flags: /qn /norestart
      uninstaller: https://downloads.sourceforge.net/projects/win32svn/files/1.8.11/Setup-Subversion-1.8.11.msi
    1.8.13:
      full_name: Subversion
      install_flags: /quiet
      installer: https://downloads.sourceforge.net/projects/win32svn/files/1.8.13/Setup-Subversion-1.8.13.msi
      locale: en_US
      msiexec: true
      reboot: false
      uninstall_flags: /qn /norestart
      uninstaller: https://downloads.sourceforge.net/projects/win32svn/files/1.8.13/Setup-Subversion-1.8.13.msi
```
