### ISSUE TITLE
[ms-vcpp-2017-redist_x64]: success but failed

### ISSUE THREAD

**Issue by rgroux** [saltstack/salt-winrepo-ng#1655]
```yaml
Function: pkg.installed
Result: False
Comment: The following packages failed to install/update: ms-vcpp-2017-redist_x64
Changes:
  ----------
  ms-vcpp-2017-redist_x64:
    ----------
    install status:
      success
```
----------------------------------------
```yaml
the problem is in the sls repo file, and the redist change the naming in the registry
sls refernce are
ms-vcpp-2017-redist_x64:
  '14.20.27508':
    full_name: 'Microsoft Visual C++ 2017 Redistributable (x64) - 14.20.27508'
```
the pkg.list_pkgs return this

>
>    Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.20.27508
>        14.20.27508.1
>    Microsoft Visual C++ 2019 X64 Additional Runtime - 14.20.27508:
>        14.20.27508
>    Microsoft Visual C++ 2019 X64 Minimum Runtime - 14.20.27508:
>        14.20.27508

it means the sls file for ms-vcpp-2017-redist_x64.sls must be like this.

```yaml
ms-vcpp-2017-redist_64:
  '14.20.27508.1':
    full_name: 'Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.20.27508'
    installer: 'https://download.visualstudio.microsoft.com/download/pr/602ece0b-dae9-4f47-84c5-240dc997483e/5a0b5cec555e06240d79eb4ac6bc8973/vc_redist.x64.exe'
    install_flags: '/quiet /norestart'
    uninstaller: 'https://download.visualstudio.microsoft.com/download/pr/602ece0b-dae9-4f47-84c5-240dc997483e/5a0b5cec555e06240d79eb4ac6bc8973/vc_redist.x64.exe'
    uninstall_flags: '/uninstall /quiet /norestart'
    msiexec: False
    locale: en_US
    reboot: False
  '14.20.27508':
....
```

the version number is 14.20.27508.**1** instead of 14.20.27508
the fullname is "Microsoft Visual C++ **2015-2019** Redistributable (x64) - 14.20.27508" instead of  "Microsoft Visual C++ 2017 Redistributable (x64) - 14.20.27508"
