### ISSUE TITLE
Allow renaming of http(s) installer files

### ISSUE THREAD

**Issue by benfiedler** [saltstack/salt-winrepo-ng#1671]
Hi,

Lately I have been working on adding some windows sls files for packages that interest me and have run into this problem on at least two of them. The source URL does not end in .exe and it seems to choke when trying a pkg.install.

e.g. for the latest opera browser:

```
opera:
  latest:
    full_name: 'Opera Web Browser'
    installer: 'https://net.geo.opera.com/opera/stable/windows'
    install_flags: '/silent /allusers=1 /launchbrowser=0 /setdefaultbrowser=0'
```

This installer URL is normally redirected via browser to a file named OperaSetup.exe, however winrepo saves it rather verbatim as "net.geo.opera.com\opera\stable\windows". When I push this sls to my windows minion and try to install, I get this in the log. I am presuming the error is because the downloaded file does not end in .exe :

`2020-02-21 16:34:47,357 [salt.loaded.int.module.cmdmod:841 ][ERROR   ][2284] Command '"C:\Windows\system32\cmd.exe" /s /c ""c:\salt\var\cache\salt\minion\extrn_files\base\net.geo.opera.com\opera\stable\windows" /silent /allusers=1 /launchbrowser=0 /setdefaultbrowser=0"' failed with return code: 1
2020-02-21 16:34:47,358 [salt.loaded.int.module.cmdmod:843 ][ERROR   ][2284] stdout: '"c:\salt\var\cache\salt\minion\extrn_files\base\net.geo.opera.com\opera\stable\windows"' is not recognized as an internal or external command,`

cache_file and cache_dir sounded promising but they also don't seem to support renaming the installer actual file. I would prefer to have a http(s) source rather than a static salt:// managed file which will grow outdated.

Is there an existing way to do this without making a custom powershell script?
