### ISSUE TITLE
jdk8.sls does not uninstall

### ISSUE THREAD

**Issue by sharkbruhaha** [saltstack/salt-winrepo-ng#1871]
The https://github.com/saltstack/salt-winrepo-ng/blob/master/jdk8.sls
does not uninstall. I've written an updated version for jdk11.0.8 and still not working.

Can someone verify if this works on their end?
Testing the `msiexec.exe /x {<uninstall-string>} /qn /norestart` in cmd.exe works, but does not in powershell. Trying to get this to work in salt is not working. It installs, but will not uninstall.

salt version 3003.1

```
jdk11:
  '11.0.8':
    full_name: 'Java(TM) SE Development Kit 11.0.8 (64-bit)'
    installer: salt://win/repo-ng/jdk/jdk-11.0.8_windows-x64_bin.exe
    install_flags: '/s ADDLOCAL="ToolsFeature,SourceFeature"'
    uninstall_flags: '/x {9CF66E0E-CABB-5A5B-81E6-52718B73CE35} /qn /norestart'
    uninstaller: 'msiexec.exe'
    msiexec: False
    locale: en_US
    reboot: False
```
