### ISSUE TITLE
Chrome reports failure after installation

### ISSUE THREAD

**Issue by TravisPaul** [saltstack/salt-winrepo-ng#332]
Installed chrome via salt and it reported failure, logged into server and it was installed correctly.  Opened chrome, set as default browser and still reports failure:

init.sls:
```YAML
chrome:
     pkg:
         - installed
```

highstate result:
```YAML
          ID: chrome
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: chrome=latest
     Started: 14:21:48.846000
    Duration: 52285.0 ms
     Changes:   
              ----------
              _comment:
                  Registry not updated.
```

Using module:
```YAML
[root@salt ~]# salt wintendo pkg.install chrome
wintendo:
    ----------
    _comment:
        Registry not updated.
```

```YAML
[root@salt ~]# salt wintendo pkg.list_pkgs
...
    chrome:
        49.0.2623.87
...
```

Version info:
```YAML
[root@salt ~]# salt -L master,wintendo test.versions_report
master:
    Salt Version:
               Salt: 2015.8.5
     
    Dependency Versions:
             Jinja2: unknown
           M2Crypto: 0.20.2
               Mako: Not Installed
             PyYAML: 3.10
              PyZMQ: 14.3.1
             Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 3.2.5
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: Not Installed
              smmap: 0.8.1
            timelib: Not Installed
     
    System Versions:
               dist: centos 6.7 Final
            machine: x86_64
            release: 2.6.32
             system: CentOS 6.7 Final
     
wintendo:
    Salt Version:
               Salt: 2015.8.5
     
    Dependency Versions:
             Jinja2: 2.7.3
           M2Crypto: Not Installed
               Mako: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.7.0
             Python: 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)]
               RAET: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.2
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.4.2
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
            libgit2: Not Installed
            libnacl: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
             pygit2: Not Installed
       python-gnupg: 0.3.7
              smmap: Not Installed
            timelib: Not Installed
     
    System Versions:
               dist:   
            machine: AMD64
            release: 2012ServerR2
             system: 2012ServerR2 6.3.9600  Multiprocessor Free
 
```
