### ISSUE TITLE
How to best handle custom installation paths

### ISSUE THREAD

**Issue by TravisPaul** [saltstack/salt-winrepo-ng#336]
I need to install most packages (aside from salt itself) into the path ```D:\Program Files``` to achieve this I have used a custom grain called ```program_files``` in my package sls files:

```YAML
nodejs:
  '5.7.1':
    full_name: Node.js
    installer: 'https://nodejs.org/dist/v5.7.1/node-v5.7.1-x64.msi'
    install_flags: 'INSTALLDIR="{{ grains['program_files'] }}\\Node.js" /qb'
    msiexec: True
    locale: en_US
    reboot: False
```

But using the grain in this fashion requires me to fork any packages that I want to change and prevents me from sharing these packages upstream.  Is there a better way to override the installation path?  I experimented with using the environ state an to override the ```%ProgramFiles%``` environment variable without any success.
