### ISSUE TITLE
Hash distribution files (feature request)

### ISSUE THREAD

**Issue by TravisPaul** [saltstack/salt-winrepo-ng#337]
In some other package building frameworks such as PKGBUILD and Pkgsrc, distribution files can be checked against a hash to ensure the file that is being installed is identical to the file used during package creation by the packager.  This seems even more valuable to salt-winrepo-ng as we are installing binaries from many other untrusted locations.

I propose something like the following
```YAML
mypkg:
  '1.0.0':
    full_name: 'My Package 1.0.0'
    installer: 
        - url: 'https://ihopethisdomaindoesntgettakenoveroneday.com/mypkg.exe'
        - sha256: 16aba5393ad72c0041f5600ad3c2c52ec437a2f0c7fc08fadfc3c0fe9641d7a3
```

One temporary workaround is to fork all desired packages on this repo and use an ```installer:``` url that points to a trusted location hosting all needed installers.
