### ISSUE TITLE
Adobe reader dc

### ISSUE THREAD

**Issue by hrumph** [saltstack/salt-winrepo-ng#373]
Hi all the adobe reader dc links are all dead (I asssume that's normal)
and there's a new one:
https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/1501020060/AcroRdrDC1501020060_en_US.exe

I think that things just changed at adobe. The version you get isn't

2015.xxx.xxxxx

Instead it has type 15.xxx.xxxx

And explanation of the new versioning stuff is here:

http://www.adobe.com/devnet-docs/acrobatetk/tools/AdminGuide/whatsnewdc.html

The long and short of it is that we probably need to make new sls file called adobe-reader-dc-classic
(or something like that).

It can start off with

```
adobereader-dc-classic:
  '15.010.20060':
    full_name: 'Adobe Acrobat Reader DC'
    installer: 'https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/1501020060/AcroRdrDC1501020060_en_US.exe'
    install_flags: '/msi EULA_ACCEPT=YES ALLUSERS=1 REMOVE_PREVIOUS=YES /qn'
    uninstaller: 'msiexec.exe'
    uninstall_flags: '/qn /x {AC76BA86-7AD7-1033-7B44-AC0F074E4100} /norestart'
    msiexec: False
    locale: en_US
    reboot: False
```
