### ISSUE TITLE
How do I run a 'dual value' or 'paired values' jinja2 for loop?

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt-winrepo-ng#40]
How can I modify this jinja2 for loop so it includes ONE build number along with ONE version number in each iteration of the loop?

So in first run of the for loop it has version set to '5.18.4' AND build set to '1805'
in second run of the for loop it should have version set to '5.20.2' AND build set to '2002'
and in third run of the for loop it should have version set to '5.22.0' AND build set to '2200'

in my salt winrepo-ng sls file. (basically a jinja2 templated salt sls file)
```
activeperl_x86:
  {% for version in '5.22.0', '5.20.2', '5.18.4' %}
  {{ version }}:
    full_name: 'ActivePerl {{ version }} Build {{ build }} (64-bit)'
    installer: 'http://downloads.activestate.com/ActivePerl/releases/{{ version }}.{{ build }}/ActivePerl-{{ version }}.{{ build }}-MSWin32-x86-64int-299195.msi'
    uninstaller: 'http://downloads.activestate.com/ActivePerl/releases/{{ version }}.{{ build }}/ActivePerl-{{ version }}.{{ build }}-MSWin32-x86-64int-299195.msi'
    install_flags: '/qn /norestart'
    uninstall_flags: '/qn /norestart'
    msiexec: True
    locale: en_US
    reboot: False
  {% endfor %}
```

In the end result the installer and uninstaller should have properly filled in URLs to match the actual URLs below.
```
http://downloads.activestate.com/ActivePerl/releases/5.18.4.1805/ActivePerl-5.18.4.1805-MSWin32-x86-64int-299195.msi
http://downloads.activestate.com/ActivePerl/releases/5.20.2.2002/ActivePerl-5.20.2.2002-MSWin32-x86-64int-299195.msi
http://downloads.activestate.com/ActivePerl/releases/5.22.0.2200/ActivePerl-5.22.0.2200-MSWin32-x86-64int-299195.msi
```  
This question is also in a gist here https://gist.github.com/TheBigBear/07c31525bf2c2b2fba82 

@eliasp ^^ @twangboy @jfindlay @UtahDave any help or hints form one of you folks?
