### ISSUE TITLE
Chocolatey as requisite in SLS

### ISSUE THREAD

**Issue by alekseyl1992** [saltstack/salt-winrepo-ng#645]
My SLS file:

```
chocolatey:
  pkg.installed:
    - require:
      - pkg: dotnet

visualstudio2015professional:
  chocolatey.installed:
    - require:
      - pkg: chocolatey
```

when I run highstate I get:

```
          ID: chocolatey
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: chocolatey=0.9.9
     Started: 17:00:22.464000
    Duration: 7612.0 ms
     Changes:
              ----------
              chocolatey:
                  ----------
                  install status:
                      success
----------
          ID: visualstudio2015professional
    Function: chocolatey.installed
      Result: False
     Comment: One or more requisite failed: tester.chocolatey
     Started:
    Duration:
     Changes:
```

please note that:
1) chocolatey actually installs and works
2) it even returns:

```
                  install status:
                      success
```

3) but salt treats this as error:
`packages failed to install/update`

I tried both installing chocolatey via chocolatey.bootstrap or using SLS as stated above. Both times choco installed and worked just fine.

May be that's because it:
https://github.com/saltstack/salt-winrepo-ng/blob/master/chocolatey.sls
actually installs the latest choco, which is 0.10, not 0.9.9 as mentioned in registry keys.

I know there is another issue about choco exit codes:
https://github.com/saltstack/salt/issues/34099

but that issue bescribes installing software with choco, whereas my - installing choco itself.

salt 2016.3.2 (Boron)
salt-minion 2016.3.2 (Boron)
minion os: Windows 7
